### ISSUE TITLE
ReferenceError: window is not defined (npm)

### ISSUE THREAD

**Issue by tommag21** [ChatCamp/ChatCamp-JavaScript-SDK#1]
As it happens on [RunKit](https://npm.runkit.com/chatcamp)

`var chatcamp = require("chatcamp")`

> ReferenceError: window is not defined

**Comment by darklrd** [comment]
ChatCamp package requires a browser or react native environment to run. If you intend to run it inside a node.js environment, then please consider using "browser-env" package along with it. Thanks.
