### ISSUE TITLE
WebSocket connection to 'wss://api.chatcamp.io/chat/1.0?app_id=6496427490540515000&user_id=1bdf6a4276201a87d8aadeac102cb056' failed: Error during WebSocket handshake: Unexpected response code: 400

### ISSUE THREAD

**Issue by linaseniorwebdev** [ChatCamp/ChatCamp-JavaScript-SDK#2]
I'm trying to use this chat function without nodejs.
All other apis work fine, but when I try to connect in client-side using code

var cc = new ChatCamp({ appId: MY_APP_ID });
cc.connect(USER_ID, function(error, user) {
	if(errror === null){
		console.log("Connected to ChatCamp")
	}
});

I got error, like

WebSocket connection to 'wss://api.chatcamp.io/chat/1.0?app_id=6496427490540515000&user_id=1bdf6a4276201a87d8aadeac102cb056' failed: Error during WebSocket handshake: Unexpected response code: 400

Anyone can explain why this happen?

**Comment by darklrd** [comment]
@linaseniorwebdev This error means that `app_id` is incorrect.
